import React, { useState, useEffect } from 'react';
import { 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, ResponsiveContainer,
  PieChart, Pie, Cell, AreaChart, Area
} from 'recharts';
import { 
  LayoutDashboard, 
  TrendingUp, 
  Activity, 
  Box, 
  ChevronDown, 
  Filter,
  Download,
  UploadCloud,
  FileJson
} from 'lucide-react';

export default function App() {
  const [dashboardData, setDashboardData] = useState(null);
  const [selectedBU, setSelectedBU] = useState('');
  const [isDropdownOpen, setIsDropdownOpen] = useState(false);

  // Helper to clean up the data (used by both auto-load and manual upload)
  const processAndSetData = (parsedData) => {
    const cleanedData = {};
    Object.keys(parsedData).forEach(buKey => {
      // 1. Clean BU Name: Remove everything starting from " Final"
      let cleanBUName = buKey.includes(' Final') ? buKey.split(' Final')[0] : buKey;
      
      // 2. Remove "No Demand" from the segmentation breakdown
      const cleanedSegmentation = parsedData[buKey].segmentation.filter(
        item => !item.name.toLowerCase().includes('no demand')
      );
      
      // Save the cleaned data
      cleanedData[cleanBUName] = {
        ...parsedData[buKey],
        segmentation: cleanedSegmentation
      };
    });

    setDashboardData(cleanedData);
    setSelectedBU(Object.keys(cleanedData)[0]);
  };

  // Auto-load data on startup (For GitHub Pages deployment)
  useEffect(() => {
    const autoLoadData = async () => {
      try {
        // In the Canvas preview environment, fetch with relative paths can throw a TypeError.
        // We wrap it in a try-catch so it gracefully falls back to the upload screen here.
        const response = await fetch('dashboard_data.json');
        if (response.ok) {
          const parsedData = await response.json();
          processAndSetData(parsedData);
        }
      } catch (err) {
        console.log("Auto-load skipped (normal in preview environment). Waiting for manual upload.");
      }
    };
    
    autoLoadData();
  }, []);

  // Handle JSON File Upload (For the Canvas preview environment)
  const handleFileUpload = (event) => {
    const file = event.target.files[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (e) => {
        try {
          const parsedData = JSON.parse(e.target.result);
          processAndSetData(parsedData);
        } catch (error) {
          console.error("Error parsing JSON:", error);
          alert("Invalid JSON file. Please upload the dashboard_data.json generated by the Python script.");
        }
      };
      reader.readAsText(file);
    }
  };

  // Custom Tooltip for Pie Chart
  const CustomTooltip = ({ active, payload }) => {
    if (active && payload && payload.length) {
      return (
        <div className="bg-slate-800 text-white p-3 rounded-lg shadow-xl border border-slate-700">
          <p className="font-semibold text-sm">{payload[0].name}</p>
          <p className="text-blue-400 font-bold text-lg">{payload[0].value.toLocaleString()} items</p>
        </div>
      );
    }
    return null;
  };

  // UPLOAD SCREEN (Shown if data hasn't been loaded yet)
  if (!dashboardData) {
    return (
      <div className="min-h-screen bg-slate-50 flex items-center justify-center font-sans" style={{ fontFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif' }}>
        <div className="bg-white p-10 rounded-2xl shadow-xl max-w-lg w-full text-center border border-slate-100">
          <div className="flex justify-center mb-6">
            <div className="text-3xl font-bold tracking-tight text-slate-900 flex items-baseline gap-1">
              <span>Thermo Fisher</span>
              <span className="text-sm font-light text-slate-500 tracking-widest">SCIENTIFIC</span>
            </div>
          </div>
          <div className="bg-red-50 p-6 rounded-full w-24 h-24 mx-auto mb-6 flex items-center justify-center">
            <FileJson size={40} className="text-red-600" />
          </div>
          <h2 className="text-2xl font-bold text-slate-800 mb-2">Load Dashboard Data</h2>
          <p className="text-slate-500 mb-8">Please upload your <code className="bg-slate-100 px-2 py-1 rounded text-slate-700">dashboard_data.json</code> to preview the dashboard here.</p>
          
          <label className="cursor-pointer bg-red-600 hover:bg-red-700 text-white px-6 py-3 rounded-xl font-semibold transition-colors shadow-md flex items-center justify-center gap-2 mx-auto w-full max-w-xs">
            <UploadCloud size={20} />
            Upload JSON File
            <input type="file" accept=".json" onChange={handleFileUpload} className="hidden" />
          </label>
        </div>
      </div>
    );
  }

  // --- MAIN DASHBOARD SCREEN ---
  const currentData = dashboardData[selectedBU];
  const BUs = Object.keys(dashboardData);

  return (
    <div className="min-h-screen bg-slate-50 text-slate-800" style={{ fontFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif' }}>
      {/* HEADER */}
      <header className="bg-white border-b border-slate-200 px-8 py-4 flex justify-between items-center sticky top-0 z-10 shadow-sm">
        <div className="flex items-center gap-3">
          <div className="flex flex-col">
            <div className="text-2xl font-bold tracking-tight text-slate-900 flex items-baseline gap-1">
              <span>Thermo Fisher</span>
              <span className="text-sm font-light text-slate-500 tracking-widest">SCIENTIFIC</span>
            </div>
            <p className="text-xs text-red-600 font-bold uppercase tracking-wider mt-1">Segmentation Dashboard</p>
          </div>
        </div>

        <div className="flex items-center gap-4">
          {/* BU Dropdown */}
          <div className="relative">
            <button 
              onClick={() => setIsDropdownOpen(!isDropdownOpen)}
              className="flex items-center gap-2 bg-slate-100 hover:bg-slate-200 text-slate-800 px-4 py-2 rounded-lg font-semibold transition-colors border border-slate-200"
            >
              <Filter size={16} className="text-red-600" />
              <span className="max-w-[200px] truncate">{selectedBU}</span>
              <ChevronDown size={16} className={`transition-transform ${isDropdownOpen ? 'rotate-180' : ''}`} />
            </button>
            
            {isDropdownOpen && (
              <div className="absolute right-0 mt-2 w-72 bg-white border border-slate-200 rounded-xl shadow-2xl overflow-hidden z-20 max-h-96 overflow-y-auto">
                {BUs.map(bu => (
                  <button
                    key={bu}
                    onClick={() => {
                      setSelectedBU(bu);
                      setIsDropdownOpen(false);
                    }}
                    className={`w-full text-left px-4 py-3 text-sm font-medium transition-colors hover:bg-red-50 hover:text-red-700
                      ${selectedBU === bu ? 'bg-red-50 text-red-700 border-l-4 border-red-600' : 'text-slate-600 border-l-4 border-transparent'}`}
                  >
                    {bu}
                  </button>
                ))}
              </div>
            )}
          </div>
          
          <button className="flex items-center gap-2 bg-red-600 hover:bg-red-700 text-white px-4 py-2 rounded-lg font-semibold transition-colors shadow-md">
            <Download size={16} />
            Export Report
          </button>
        </div>
      </header>

      <main className="p-8 max-w-7xl mx-auto space-y-8">
        {/* KPI CARDS */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="bg-white rounded-2xl p-6 shadow-sm border border-slate-100 flex items-center gap-5 transform transition-transform hover:-translate-y-1 hover:shadow-md">
            <div className="bg-slate-100 p-4 rounded-xl border border-slate-200">
              <Box size={28} className="text-slate-700" />
            </div>
            <div>
              <p className="text-sm font-bold text-slate-400 uppercase tracking-wider">Total Evaluated</p>
              <h3 className="text-3xl font-extrabold text-slate-800">{currentData.kpis.totalSKUs.toLocaleString()}</h3>
            </div>
          </div>
          
          <div className="bg-white rounded-2xl p-6 shadow-sm border border-slate-100 flex items-center gap-5 transform transition-transform hover:-translate-y-1 hover:shadow-md">
            <div className="bg-slate-100 p-4 rounded-xl border border-slate-200">
              <Activity size={28} className="text-slate-700" />
            </div>
            <div>
              <p className="text-sm font-bold text-slate-400 uppercase tracking-wider">High Variability %</p>
              <h3 className="text-3xl font-extrabold text-slate-800">{currentData.kpis.avgVariability}</h3>
            </div>
          </div>

          <div className="bg-white rounded-2xl p-6 shadow-sm border border-slate-100 flex items-center gap-5 transform transition-transform hover:-translate-y-1 hover:shadow-md">
            <div className="bg-red-50 p-4 rounded-xl border border-red-100">
              <TrendingUp size={28} className="text-red-600" />
            </div>
            <div>
              <p className="text-sm font-bold text-slate-400 uppercase tracking-wider">Intermittent %</p>
              <h3 className="text-3xl font-extrabold text-slate-800">{currentData.kpis.highlyIntermittent}</h3>
            </div>
          </div>
        </div>

        {/* MAIN CHARTS GRID */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          
          {/* SHEET 1: SEGMENTATION BREAKDOWN */}
          <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6 lg:col-span-1 flex flex-col hover:shadow-md transition-shadow">
            <h2 className="text-xl font-bold text-slate-800 mb-6 flex items-center gap-2">
              <div className="w-2 h-6 bg-red-600 rounded-full"></div>
              1. Segmentation Breakdown
            </h2>
            <div className="flex-grow min-h-[300px]">
              <ResponsiveContainer width="100%" height="100%">
                <PieChart>
                  <Pie
                    data={currentData.segmentation}
                    cx="50%"
                    cy="50%"
                    innerRadius={70}
                    outerRadius={110}
                    paddingAngle={5}
                    dataKey="value"
                    stroke="none"
                  >
                    {currentData.segmentation.map((entry, index) => (
                      <Cell key={`cell-${index}`} fill={entry.color} />
                    ))}
                  </Pie>
                  <RechartsTooltip content={<CustomTooltip />} />
                </PieChart>
              </ResponsiveContainer>
            </div>
            <div className="mt-4 space-y-3">
              {currentData.segmentation.map((item, i) => (
                <div key={i} className="flex justify-between items-center text-sm">
                  <div className="flex items-center gap-2">
                    <div className="w-3 h-3 rounded-full shadow-sm" style={{ backgroundColor: item.color }}></div>
                    <span className="font-medium text-slate-600">{item.name}</span>
                  </div>
                  <span className="font-bold text-slate-800">{item.value.toLocaleString()}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="lg:col-span-2 space-y-8 flex flex-col">
            
            {/* SHEET 2: INTERMITTENCY SUMMARY & BANDS */}
            <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6 flex-grow hover:shadow-md transition-shadow">
              <h2 className="text-xl font-bold text-slate-800 mb-6 flex items-center gap-2">
                <div className="w-2 h-6 bg-blue-600 rounded-full"></div>
                2. Intermittency Summary & Bands
              </h2>
              <div className="h-[250px]">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={currentData.intermittency} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                    <XAxis dataKey="band" axisLine={false} tickLine={false} tick={{ fill: '#64748b', fontSize: 12 }} dy={10} />
                    <YAxis axisLine={false} tickLine={false} tick={{ fill: '#64748b', fontSize: 12 }} />
                    <RechartsTooltip 
                      cursor={{ fill: '#f8fafc' }}
                      contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)' }}
                    />
                    <Bar dataKey="count" fill="#2563eb" radius={[6, 6, 0, 0]} barSize={40} name="Number of Items" />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* SHEET 3: VARIABILITY SUMMARY & BANDS */}
            <div className="bg-white rounded-2xl shadow-sm border border-slate-100 p-6 flex-grow hover:shadow-md transition-shadow">
              <h2 className="text-xl font-bold text-slate-800 mb-6 flex items-center gap-2">
                <div className="w-2 h-6 bg-teal-500 rounded-full"></div>
                3. Variability Summary & Bands
              </h2>
              <div className="h-[250px]">
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={currentData.variability} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                    <defs>
                      <linearGradient id="colorCount" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="#14b8a6" stopOpacity={0.3}/>
                        <stop offset="95%" stopColor="#14b8a6" stopOpacity={0}/>
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                    <XAxis dataKey="band" axisLine={false} tickLine={false} tick={{ fill: '#64748b', fontSize: 12 }} dy={10} />
                    <YAxis axisLine={false} tickLine={false} tick={{ fill: '#64748b', fontSize: 12 }} />
                    <RechartsTooltip 
                      contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgb(0 0 0 / 0.1)' }}
                    />
                    <Area type="monotone" dataKey="count" stroke="#14b8a6" strokeWidth={3} fillOpacity={1} fill="url(#colorCount)" name="Number of Items" />
                  </AreaChart>
                </ResponsiveContainer>
              </div>
            </div>

          </div>
        </div>
      </main>
    </div>
  );
}